### ISSUE TITLE
Where to buy this CPU ?

### ISSUE THREAD

**Issue by Martoni** [efabless/picorv32-soc-raven#2]
Is it possible to buy this proc and/or a devkit ?

**Comment by RTimothyEdwards** [comment]
At the moment, no, because we had a limited number (50) of chips from the initial shuttle run and an even more limited number (5) of assembled development boards.  However, we are getting several hundred additional parts from the foundry that are currently in process.  Please contact support@efabless.com and ask to be informed when additional development boards are available.
